{% set name = "quickBayes" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quickbayes-{{ version }}.tar.gz
  sha256: 89d87603461fb4302915e95fa90ab96f0b509c64ce7331659f4ba4cf44307cf0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pybind11
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  imports:
    - quickBayes
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ISISNeutronMuon/quickBayes
  summary: A Bayesian fitting package used for model selection and grid searches of fits for neutron and muon data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AnthonyLim23
    - thomashampson
    - jclarkeSTFC
